.github/pull_request_template.md

In order to promote more consistent PR's and help us remember and communicate all the aspects of the work being reviewed, we need prompting with some sort of template.  GitHub's PR template is our tool of choice.
This PR is a prerequisite for DPC-1249; further work will be done for this ticket.
- Add a PR template
This is a text artifact of the repository only, intended to increase security awareness and reduction of risk.  It does not contain PII/PHI.
This PR is based on the PR template being committed!
Are there typos, concerns, items that need to be further customized for DPC, etc?

DPC-1249 Configuration: Add request template

---

_includes/_hero.html
_includes/_nav.html
_layouts/page-info.html
_sass/components/_accordions.scss
_sass/components/_hero.scss
common/faq.html
common/guide.md
index.html

As we open up our expanded production pilot, we want to update the language of the static site to reflect DPC's current state. 
- Add banner announcing production pilot
- Change language on home page
- FAQ: add questions & organize by topic
- Add introductory Docs paragraph

DPC-781: Keep static site updated with web app

---

common/guide.md

- Update documentation in static site to keep it in sync w/ current web app

DPC-915: Web updates

---

Dockerfiles/Dockerfile.static_site
_includes/_head.html
_version_config.yml

Paired with [DPC-904 in dpc-ops repo](https://github.com/CMSgov/dpc-ops/pull/290).
The DPC static site CI/CD is in place but we are currently not adding a version meta tag in the site.  This means we never know which version of the static site is “live” in production.
- Embed version meta tag as part of local build.
Referencing [BCDA-3368](https://github.com/CMSgov/bcda-static-site/pull/71).

DPC-904: Add version metadata to static site deployment

---

common/guide.md

Update the user guide language with approved edits: https://docs.google.com/document/d/1g7nhqhXjkI7osew6tgkTxuIeLM58L1p_gupTlOImOnk/edit?ts=60005403#
**Before**
**After**

DPC-1086: Update language in static site

---

.github/pull_request_template.md
.gitignore
common/guide.md

There is a typo in the comments of the sample Javascript for creating tokens.
* Correct the spelling
* Correct the Jira link in the PR template
* Have Git ignore the /.idea folder (for JetBrains IDEs such as IntelliJ, RubyMine, etc.)
No new dependencies are added, and no capabilities are changed.
* Any other typos to catch while we're at it?
* Double-check the Jira link in the PR template 😄

DPC-1133: Spelling/link corrections

---

_config.yml

The code which defines the list of files to exclude from `_site` needs to be updated.
Add files to be excluded under `_config`
- package.json
- package-lock.json
- ops/
- scripts/
- README.md
- Dockerfiles/
- docker-compose.yml
- Makefile

[DPC-1165] Fix: Update list of files to exclude under _config

---

_sass/components/_navbar.scss

Currently the headers (Home, Documentation, Frequently Asked Questions) in the webapp do not have the same formatting as the static site.
The long-story-short reason why this is happening: the way Jekyll compiles CSS is slightly different than Rails, hence the small but noticeable differences.
I adjusted the variables to make it a cleaner transition.
**Before**
**After**

DPC-1174: Fix headers in webapp

---

_config.yml
index.html

Fixes [DPC-1227](https://jira.cms.gov/browse/DPC-1227)
DPC's meta/description was formerly filled in with filler text. Updated with existing language from webapp.
- Old text: "Write an awesome description for your new site here . . ." to
- Updated text: "Data at the Point of Care is a CMS pilot API program that enables healthcare providers to deliver high quality care directly to Medicare beneficiaries by making a patient’s Medicare claims data available to the provider for treatment needs."

DPC-1227 Update _config.yml

---

_includes/_google-analytics.html
_includes/_head.html

Right now, the Google Analytics account is only tracking user interactions with the DPC Implementation Guide. We should be tracking all pages of the static site and webportal.
- Add google analytics to the static site
- Paired with [PR for the implementer application](https://github.com/CMSgov/dpc-app/pull/1311)
Google Analytics is tracking user activity for entire web experience.

DPC-1397: Update webapp to work with Google Analytics

---

_includes/_google-analytics.html

In coordination with [1450 - DPC app](https://github.com/CMSgov/dpc-app/pull/1330). SonarQube flagged our Google Analytics script header in the web app as noncompliant.
replace existing google analytics script with:
```
<script src="https://www.googletagmanager.com/gtag/js?id=UA-144775756-1" integrity="sha384-a2mjMPSjfjBRbLs6v9TwNfk4b6Yjlh+f2DZp0y1P76DY3TAPpVpnfYC0nN3jtxcF" crossorigin="anonymous"></script>
```
- Change link in static site.
- [Change link](https://github.com/CMSgov/dpc-app/pull/1330) in `dpc-web`, `dpc-admin`, `dpc-impl`.
- Any external scripts-the Google Analytics tag in particular-include an integrity= parameter
- Pages continue to load without error (e.g. the hash matches that of the actual script) when tested with multiple browser types

DPC-1450: Address Sonar SRI issue for Google Analytics script

---

index.html

Resolve failed 508 compliance test

---

common/tos.md

Terms of Service has changed for DPC v2
Updated the Terms of Service language to reflect DPC v2 update
Updated the Terms of Service language to reflect DPC v2 update
Confirmation that the update went through, please and thank you!

Update Terms of Service

---

common/tos.md

Updated Terms of Service 
- removed bolded language
- update language cases and acronyms
- removed bolded language
- update language cases and acronyms
- 
This update is for language on the static site/terms of service and does not have any security concerns.
I did not compete any security checklists because this is a language update. Please let me know if it is needed otherwise.
none, thanks!

DPC-1656 StaticSite: Update ToS

---

Makefile

The IG jar moved again...
Change to point to the official IG publisher github latest release link
Don't believe any security concerns are present, we are using the official github repo https://github.com/HL7/fhir-ig-publisher

DPC-1915 update ig jar location

---

common/docsV1.md

Documentation updates to allow easier copy and pasting of cURL commands, and updating urls to ensure accuracy of required parameters.

Multiple Fixes: DPC-2356, DPC-2486, DPC-2432, DPC-2433, DPC-2431

---

_includes/_google-analytics.html
_includes/_head.html
implementation_guide/framework/_includes/analytics.html

Google Analytics needs to be removed from the static site.
Deleted the `_google_analytics.html` as well as the references to it within the `_head.html`
and also removed the `analytics.html` from the `framework/_includes` folder
The owner of the Google Analytics instance that was being used needs to verify there is no more data being sent.

removing GA

---

ops/release.sh

removed git tag from release.sh
git tag -a -m"$PROJECT_NAME release $NEWTAG" -s "$NEWTAG"

git tag was removed from release.sh

---

common/docsV1.md

Updated the instructions for downloading the snippet.txt file to match the following acceptance criteria.
Adding the curl command to the static site as well as how to verify the correct type of text file on Mac and Linux
Update static site with instructions on how to download the snippet.txt file from a terminal environment
You can use this cURL to get the file from GitHub:
curl -JLO https://raw.githubusercontent.com/CMSgov/dpc-app/master/dpc-web/public/snippet.txt 
If you are using bash, zsh, or similar you can check the file type with this command (will not work in cmd or powershell)
file snippet.txt 
and this should output the following type:
snippet.txt: ASCII text, with no line terminators 
If `with no line terminators` is not present, the keys and signature will not properly …

LG Static Site Update

---

common/faq.html

Updating FAQ to inform users on HITRUST certification. 
New entry into FAQ Page
New entry into FAQ Page

DPC-2809 Update FAQ with HITRUST information

---

common/docsV1.md
common/pilot.html

Changes based on feedback from CMS Product Owner, and DPC Content manager.

DPC-2945 Updates to documentation and about pages (continuation)

---

common/docsV1.md

Casing issue
Fixed a casing that was missed

DPC-2945 Fixing missed casing change.

---

_includes/_hero.html
index.html

Content changes to Home Page and banner as laid out in https://confluence.cms.gov/display/DAPC/DPC+Website+Copy and https://confluence.cms.gov/display/DAPC/Home+Page
See https://confluence.cms.gov/display/DAPC/Home+Page for detailed changes.

👌 IMPROVE: Update Home Page content

---

.pre-commit-config.yaml

* adding gitleaks precommit config to all repos

adding gitleaks precommit config

---

.github/pull_request_template.md

* Adds standard security section to pull request template.

DPC-3380: PR Templates - Security Section

---

common/docsV1.md
index.html

https://jira.cms.gov/browse/DPC-3402
Update BCDA card information.

Update BCDA card

---

_includes/_hero.html
common/update-page.md
package-lock.json
scripts/build_and_test.sh

https://jira.cms.gov/browse/DPC-3434
Banner and updates page now reflect pause in onboarding.
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)

Update site to pause onboarding

---

_includes/_hero.html
_sass/components/_hero.scss
common/update-page.md

https://jira.cms.gov/browse/DPC-3483
Content updates to the hero bar and updates page (See [here](https://confluence.cms.gov/pages/viewpage.action?spaceKey=DAPC&title=%28V2%29+DPC+Onboarding+Pause+Update) for requested changes).
Asked to make updates detailing our current onboarding pause for end users.
Tests pass and content matches what was requested.  

Hero bar and updates page content updates

---

common/update-page.md

Ticket forthcoming, wanted to get the PR up quickly in the meantime.
Removed "-The DPC team" signature from updates page.
See Slack request [here](https://cmsgov.slack.com/archives/CJL0FRN2E/p1690992584190649?thread_ts=1690927692.253939&cid=CJL0FRN2E)
Signature is gone

Removed -dpc team signature from updates-page.md

---

_config.yml
common/faq.html

https://jira.cms.gov/browse/DPC-3606
Capitalized "Frequently Asked Questions" in faq page.
Fixing some grammar.
Ran locally.

[DPC-3606] Capitalized Frequently Asked Questions in faq.html

---

_layouts/default.html
assets/js/global.js
assets/js/navbar.js
common/docsV1.md

https://jira.cms.gov/browse/DPC-3883
EventListeners were added to links on all pages, firing appropriate utag.link events based on location of link in page and link destination.
Additional clarification in [Slack](https://cmsgov.slack.com/archives/CJL0FRN2E/p1710781202151979).
Manual testing of all link types using [Tealium instructions](https://confluence.cms.gov/display/BLSTANALYT/Viewing+the+Tealium+Data+Layer).

DPC-3883 Track internal clicks

---

common/docsV1.md

https://jira.cms.gov/browse/DPC-4021
Removed line about emailing DPC to be added to production queue.
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)

Remove line about emailing DPC

---

common/docsV1.md
common/pilot.html
ops/Jenkinsfile.continuous_delivery

https://jira.cms.gov/browse/PLT-326
Reference to master branch was changed to main
Github repository master branch renamed to main. changes made to reference main in jenkins instead of master
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)

modify reference of  master branch to main

---

common/docsV1.md

https://jira.cms.gov/browse/DPC-4107
Updated instructions for uploading a public key, creating an attestation, and deleting a group.
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
Uploading a public key
Creating an attestation
Deleting a group

[DPC-4107] Update docsV1.md

---

.github/workflows/broken-link-check.yml
common/docsV1.md

https://jira.cms.gov/browse/3596
Previous workflow sent a Slack message regardless of whether the test succeeded or not. Now it only sends on failures.

[DPC-3596] Fix workflow logic

---

.github/workflows/broken-link-check.yml
.lycheeignore
Makefile
scripts/build_and_test.sh

https://jira.cms.gov/browse/...

Update Docker commands

---

.lycheeignore
README.md

https://jira.cms.gov/browse/...

Update broken link

---

common/docsV1.md

https://jira.cms.gov/browse/DPC-4328
Extra content additions asked for after merging https://github.com/CMSgov/dpc-static-site/pull/136.
CMS asked for some additional language about using the vault to ensure secrets aren't synced to the cloud.
Ran locally.

[DPC-4328] Content updates

---

common/docsV1.md

https://jira.cms.gov/browse/DPC-4665
- Update copy surrounding the Gender bullet point, under the Add A Patient header.
This brings our documentation into conformance with a recent [Executive Order](https://www.whitehouse.gov/presidential-actions/2025/01/defending-women-from-gender-ideology-extremism-and-restoring-biological-truth-to-the-federal-government/), reflecting changes to our data source.

[DPC-4665] Update Gender bullet point in documentation

---

.github/workflows/deploy.yml

https://jira.cms.gov/browse/PLT-657
references to ab2d-bcda-dpc-platform renamed to cdap
we are renaming the ab2d-bcda-dpc-platform repo to cdap
upon approval, ab2d-bcda-dpc-platform repo will be renamed to cdap and workflow re-ran, if successful PR merged if not ab2d-bcda-dpc-platform repo rename to cdap reverted while investigating why workflow failed

PLT-657:Rename the public platform github repo
