CMSgov/dpc-static-site

.gitignore, assets/downloads/jwt.html
The JWT Tool was not adding an `aud` claim to the JWT that was generated.
In addition, the `aud` claim is environment-specific, so there needed to be a way to select which environment to use when generating the JWT.
- added a select for the environment: `Sandbox` or `Production`
- added `aud` claim to JWT generator
The URL in the `aud` claim includes the environment. For example, if the env is `prod-sbx` (Sandbox), the claim will have the value `https://sandbox.dpc.cms.gov/api/v1/Token/auth`. For production, the value should be `https://dpc.cms.gov/api/v1/Token/auth`
No security implications.
Tested by using the generator to create JWTs for various environments and then validated those JWTs using Postman.
All tests were successful.
Any, particularly if the select should be styled …
=> DPC-810 fix: Add `aud` claim to JWT Tool

assets/downloads/jwt.html
The url for `prod` actually needs to include `prod`.
- add `prod` value to select
- move the `.` to the url when being concatenated
No concerns
Any
=> DPC-810 fix: use `prod` for prod url

ops/Jenkinsfile.continuous_delivery, ops/github_release.py, ops/release.sh
In preparation for separating the DPC Static Site from the DPC API, we need a tag/release/deployment strategy.  
- Added scripts to be used in tagging/releasing (via Github) the static site.
- Added a Jenkins job for tagging/releasing (via Github) the static site (which make use of the scripts referenced above) as part of https://github.com/CMSgov/dpc-ops/pull/261
- Added a Jenkins job to handle CI/CD to the `stage` environment (in Akamai NetStorage) on merge to `master`
- Added a Jenkins job to deploy to Akamai NetStorage as part of https://github.com/CMSgov/dpc-ops/pull/261
- Updated Jenkins image to include `rsync`, which is used to push the static site to Akamai NetStorage as part of https://github.com/CMSgov/dpc-ops/pull/261
Note: all scripts follow the same pattern that is used on …
=> Implement Tagging and CI/CD for Static Site

ops/Jenkinsfile.continuous_delivery
The DPC Static Site continuous delivery job should be based only on polling `master`, but our job was erroneously polling based on an env var that was never being set.
- Updated the continuous delivery polling for `dpc-static-site` to align with the continuous delivery configuration for `dpc-app` and `dpc-ops`
Executed in Jenkins [here](https://management.dpc.cms.gov/job/DPC%20-%20Static%20Site%20Continuous%20Delivery/4/).
Please review.
=> Fix static site continuous delivery

common/guide.md
An automated 508 compliance scan of the DPC site found two instances of an error in the content structure, where an <h4> tag was nested in an <h2> tag without an intervening <h3>.
* Move rogue <h4> tags up to be <h3> tags.
Lines 1665 and 1694 on guide.md have been changed from <h4> to <h3> tags. 
The user guide no longer skips heading levels.
Confirm that the page now nests properly.
Let me know how to run another 508 scan to confirm we've fixed the error.
=> DPC-1269: correct semantic html nesting on user guide

common/guide.md
Currently, the user guide does not supply parameters or syntax for use of the _type query parameter.
Add language that clearly shows how the _type query parameter can be used to specify one or two resources to export.
Examples using Explanation of Benefit, Patient, and Coverage are provided, with additional explanatory language around the function of _type.
None; new static site language only
_type information in the user guide reflects parameters of Explanation of Benefits, Patient, and Coverage. New language can be used to correctly request parametrized data.
- Does the English syntax make sense? Is it clear?
- Does the sample code make sense? Can you use it to make the request it says you can make?
=> DPC-1373: Add information on specifying _type parameter

_config.yml, _includes/_hero.html, common/docsV1.md, common/faq.html, common/pilot.html
We want to replace the airtable form links in the static site, since they could pose a potential security risk, and replace them with email links instead.
- Update banner to point to pilot page instead of faq page.
- Update pilot page airtable links to use email link instead.
- Update docs page airtable link to use email link instead.
- Update faq page airtable link to use email link instead.
All mentions of the airtable url has been removed and replaced with email links instead.
General feedback as always. I have not found any other mentions of the airtable besides what has been described in the ticket.
=> dpc-1889 Feature: Remove app links

common/docsV1.md
Fixed the curl command with /ap1/v2/Token/auth by adding a `\` to the end of the line containing Post
- Fix the syntax of the curl command by adding a backslash
- Line 501 added a `\` at the end of the line
- Syntax change to the existing content and does not expose any new security vulnerabilities
- Passes the build and test with no issues
- Ability to build without any errors
(getting the DPC static site repo setup along with going through the process of making a change then deploying)
=> DPC-2189: Fix Curl Command

common/data.md, common/docsV1.md, common/docsV2.md, common/faq.html, common/pilot.html, common/tos.md, common/update-page.md
Static site pages with permalinks that have no file extension do not get picked up in AWS 
* Update page permalinks to include .html - Since the built files have the .html extension when we push them to S3, the links must have the extension as well
* Should not affect the SS in Akamai
=> Update page permalinks

_includes/_footer.html, common/pilot.html
https://jira.cms.gov/browse/DPC-3595
- Fix broken links on the pilot page and footer
There are two broken links that have been on the website. I used htmlchecker to discover these:
```
$ bundle add htmlchecker
$ docker-compose -f docker-compose.yml build static_site 
$ docker-compose -f docker-compose.yml run --rm static_site
$ bundle exec htmlproofer --assume_extension '.html' --checks 'Links' ./_site
```
It outputs a bunch of info, but the main interests for broken links are issues related to `status code 404`.
Checked the two new links manually.
=> DPC-3595: Fix broken links flagged by htmlchecker

common/data.md, common/docsV1.md
https://jira.cms.gov/browse/DPC-3649
References to http://ndjson.org replaced with https://github.com/ndjson/ndjson-spec
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
Grepped the directory before and after. Before (that is, on master) I found four instances across two files. After changes, I found no references to ndjson.org.
`grep -ri --exclude-dir ".git" "ndjson.org" .`
Also verified links locally at http://localhost:4001/data.html and http://localhost:4001/docsv1.html
=> DPC-3649 replace ndjson.org with github/ndjson-spec

docker-compose.yml
https://jira.cms.gov/browse/DPC-3779
- Set JEKYLL_ENV so it's used when building the docker image
The JEKYLL_ENV isn't read by docker (even it's set in the local environment), so `jekyll.environment` always evaluates to `development`.
Build image:
```
export JEKYLL_ENV=prod
docker-compose -f docker-compose.yml build static_site
```
Then started a container and checked the _site/index.html to verify that it's using the prod tag for Adobe Analytics.
Also deployed to stage and confirmed it's using the `qa` URL.
=> DPC-3779: Set JEKYLL_ENV when building docker image

_includes/_head.html, _layouts/default.html
https://jira.cms.gov/browse/DPC-2979
- default layout changed to use /prod/ instead of /qa/ as src_url for calls
- shared header changed to pull in /prod/ instead of /qa/ JavaScript file
Sandbox is considered production in terms of end users
Impossible to test until rollout
=> DPC-3979 Change sandbox to use prod tealium

_includes/_head.html, _layouts/default.html
This reverts commit e422f2a818d0906dbea695cccbda278ae3f31021.
https://jira.cms.gov/browse/DPC-3979
Changes rolled back
Confusion over "stage" and "sandbox" led to inappropriate rollout.
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)
=> Revert "DPC-3979 Change sandbox to use prod tealium (#106)"

_includes/_footer.html
https://jira.cms.gov/browse/3050
Removes MyMedicare.gov from page footer.
The footer previously linked to both Medicare.gov and MyMedicare.gov, the latter of which is deprecated and resolves to the login page for Medicare.gov.
Previous footer:
Updated footer:
=> [DPC-3050] Remove MyMedicare from footer

.github/workflows/check_508_compliance.yml, .github/workflows/ci-workflow.yml
https://jira.cms.gov/browse/DPC-4438
Added check_508_compliance workflow.
We are moving our jobs from Jenkins to github actions. This is a clone of [Jenkinsfile.static_site_508_compliance](https://github.com/CMSgov/dpc-ops/blob/main/jenkins_files/Jenkinsfile.static_site_508_compliance)
Forced run worked: https://github.com/CMSgov/dpc-static-site/actions/runs/12380895523
Forced run with failure (running on ubuntu-latest meant it was blocked, so it tested the Cloudfront 403 response): https://github.com/CMSgov/dpc-static-site/actions/runs/12379865142/job/34554969116
=> DPC-4438 Check static site for 508 compliance via github actions

.github/workflows/check_508_compliance.yml, .github/workflows/deploy.yml
No ticket
Slack stanzas added to deploy and 508 compliance check
Jenkins jobs sent messages to slack after deploys and 508 checks.
Tagging will send message from deploy workflow.
Ran 508 check and deploy and success messages went to slack:
508: [run](https://github.com/CMSgov/dpc-static-site/actions/runs/12657523586) [slack](https://cmsgov.slack.com/archives/CMC1E4AEQ/p1736276157869379)
deploy: [run](https://github.com/CMSgov/dpc-static-site/actions/runs/12657691685) [slack](https://cmsgov.slack.com/archives/CMC1E4AEQ/p1736276913373869)
=> Send Slack messages from Github Actions

.github/workflows/check_508_compliance.yml
No Ticket
Target base url set in one step for use in later steps
The slack message for success/failure of the 508 compliance check was using the url from the input, but cron does not set inputs. Instead, I am setting the 
Checks ran with appropriate messages
=> Fix 508 Static Site compliance check success message when run from cron

ig/qa.html, implementation_guide/README.md
https://jira.cms.gov/browse/...
Updated Readme.md and qa.html to point to correct wiki location confluence.hl7.org
The implementation guide includes links to wiki.hl7.org, which has been migrated to confluence.hl7.org. The wiki no longer has a valid certificate, which is causing issues with the link checker. The page on the wiki has a link to the relevant confluence page.
No references to older link in teh static site project
=> DPC:4561 Updated Readme.md and qa.html to point to correct wiki location confluence.hl7.org

.github/workflows/broken-link-check.yml, .github/workflows/ci-workflow.yml
https://jira.cms.gov/browse/DPC-4692
Pin `lycheeverse/lychee-action` at CDAP suggestion. [Slack convo here](https://cmsgov.slack.com/archives/C04UG13JF9B/p1747669315625319)
We need permission to run this action on the static-site, and CDAP recommended we pin it to prevent hijacking.
=> [dpc-4692] Pin lychee-action

.github/workflows/deploy-gf.yml, .github/workflows/release-gf.yml, common/docsV1.md
Add deploy-gf and release-gf workflows.
https://jira.cms.gov/browse/DPC-4692
Added Greenfield version of reply and release workflows.
We need to be able to deploy the static site in the new GF accounts.
Requires https://github.com/CMSgov/dpc-ops/pull/814
* Successfully cut new release and tag [r55](https://github.com/CMSgov/dpc-static-site/releases/tag/r55).
* Created a bucket in dev and deployed to it ([successful workflow here](https://github.com/CMSgov/dpc-static-site/actions/runs/15115140880)):
=> [dpc-4692] Add release-gf workflow

.github/workflows/deploy-gf.yml, .github/workflows/release.yml
https://jira.cms.gov/browse/DPC-4737
- Updated deploy-gf.yml to make work
Simplified naming standard with 'sandbox' as environment. CloudFront distribution available, but had to be found by origin instead of domain name.
GHA ran successfully.
=> DPC-4737 Greenfield deploy static site updates

.github/workflows/broken-link-check.yml, .github/workflows/ci-workflow.yml
https://jira.cms.gov/browse/DPC-4709
For the Broken Link Check GHA: 
- Replace a hardcoded Slack webhook URL with a reference to a GH secret. 
- Update workflow logic, so that it does not skip over Send Slack Alert step on check failure
- Update slack alert payload to reflect input variables in Slack workflow
- Temporarily remove broken links check from ci-workflow
Hardcoding gha webhooks on a publicly viewable repository leaves us open to abuse.
In the process of resolving this issue, I found that the slack alert was not being triggered even with the correct webhook URL. Once I resolved that problem, I also found that the alert was not showing up with any detail on the failed run. 
Finally, as a result of the alert just failing for so long, we have a number of broken links that were not …
=> [DPC-4709] Use secret for broken link check slack webhook URL

.github/workflows/broken-link-check.yml, .github/workflows/check_508_compliance.yml, .github/workflows/ci-workflow.yml, .github/workflows/deploy.yml
https://jira.cms.gov/browse/DPC-4772
Update remote GHA to uses SHA hashes instead of version numbers.
Using hashes is more secure in case the GHA is ever compromised, so we've been making this change across all DPC repos.
Successfully ran all updated workflows:
Broken link check: https://github.com/CMSgov/dpc-static-site/actions/runs/17869408204
508 Compliance: https://github.com/CMSgov/dpc-static-site/actions/runs/17869576022
CI Workflow: https://github.com/CMSgov/dpc-static-site/actions/runs/17869386888
Deploy (to sandbox): https://github.com/CMSgov/dpc-static-site/actions/runs/17869703165
=> Update remote GHA to use SHA for versioning
